import type { SiteData } from '@/lib/types';
import { FEATURE_FLAGS } from './feature-flags';

export const DEFAULT_SITE_CONTENT: SiteData = {
  brand: {
    name: { es: 'GlobalGates Agency', en: 'GlobalGates Agency', fr: 'GlobalGates Agency' },
    tagline: { es: 'Estrategia digital con IA para hacer crecer tu negocio.', en: 'AI-powered digital strategy to grow your business.', fr: 'Strategie numerique pilotee par IA pour faire croitre votre entreprise.' },
    heroTitle: { es: 'Transforma tu negocio con Inteligencia Artificial', en: 'Transform Your Business with Artificial Intelligence', fr: 'Transformez votre entreprise avec l\'Intelligence Artificielle' },
    heroSubtitle: { es: 'Estrategias de marketing digital, automatizacion y agentes IA para empresas que quieren crecer.', en: 'Digital marketing strategies, automation and AI agents for businesses that want to grow.', fr: 'Strategies de marketing numerique, automatisation et agents IA pour les entreprises qui veulent croitre.' },
    heroImage: '/globalgates-hero.jpg',
    colors: { gold: '#D4AF37', ink: '#1a1a2e', bg: '#f8f9fa', slate: '#64748b' },
  },
  agentPersona: {
    firstName: 'Aria',
    lastName: 'Gates',
    avatar: '/agent-avatar.png',
  },
  services: [
    {
      id: 'solution-sm',
      visible: true,
      title: { es: 'Marketing en Redes Sociales', en: 'Social Media Marketing', fr: 'Marketing sur les Reseaux Sociaux' },
      bullets: [
        { es: 'Gestion profesional de Instagram, Facebook, TikTok y LinkedIn.', en: 'Professional management of Instagram, Facebook, TikTok and LinkedIn.', fr: 'Gestion professionnelle d\'Instagram, Facebook, TikTok et LinkedIn.' },
        { es: 'Contenido estrategico generado con IA y revisado por expertos.', en: 'Strategic content generated with AI and reviewed by experts.', fr: 'Contenu strategique genere par IA et revise par des experts.' },
        { es: 'Reportes de desempeno mensuales con metricas clave.', en: 'Monthly performance reports with key metrics.', fr: 'Rapports de performance mensuels avec indicateurs cles.' },
      ],
      features: [FEATURE_FLAGS.AI_MARKETING_ASSISTANT, FEATURE_FLAGS.AI_CONTENT_GENERATION],
      agents: [{ id: 'ai_marketing_assistant', name: 'AI Marketing Assistant', enabled: true }],
    },
    {
      id: 'solution-seo',
      visible: true,
      title: { es: 'SEO y Posicionamiento Web', en: 'SEO and Web Positioning', fr: 'SEO et Positionnement Web' },
      bullets: [
        { es: 'Analisis de competencia y palabras clave con IA.', en: 'AI-powered competitor and keyword analysis.', fr: 'Analyse de la concurrence et des mots-cles par l\'IA.' },
        { es: 'Optimizacion on-page y creacion de contenido estrategico.', en: 'On-page optimization and strategic content creation.', fr: 'Optimisation on-page et creation de contenu strategique.' },
        { es: 'Monitoreo de rankings y reportes de visibilidad mensuales.', en: 'Ranking monitoring and monthly visibility reports.', fr: 'Suivi du classement et rapports de visibilite mensuels.' },
      ],
      features: [FEATURE_FLAGS.ANALYTICS_INTEGRATION],
    },
    {
      id: 'solution-ads',
      visible: true,
      title: { es: 'Publicidad Digital (Meta y Google Ads)', en: 'Digital Advertising (Meta & Google Ads)', fr: 'Publicite Numerique (Meta et Google Ads)' },
      bullets: [
        { es: 'Campanas segmentadas en Facebook, Instagram y Google.', en: 'Targeted campaigns on Facebook, Instagram and Google.', fr: 'Campagnes ciblees sur Facebook, Instagram et Google.' },
        { es: 'Optimizacion continua de anuncios para maximizar el ROI.', en: 'Continuous ad optimization to maximize ROI.', fr: 'Optimisation continue des annonces pour maximiser le ROI.' },
        { es: 'Integra con IA para ajuste automatico de pujas y audiencias.', en: 'AI integration for automatic bid and audience adjustment.', fr: 'Integration IA pour ajustement automatique des encheres et audiences.' },
      ],
      features: [FEATURE_FLAGS.AI_CAMPAIGN_PLANNER],
    },
  ],
  products: [
    {
      id: 'prod_social_1',
      visible: true,
      type: 'sub',
      price: 150,
      name: { es: 'Plan Social Inicial', en: 'Starter Social Plan', fr: 'Plan Social Initial' },
      badge: { es: 'Inicial', en: 'Starter', fr: 'Debutant' },
      note: { es: '1 red social, 8 posts, 4 historias, reporte simple.', en: '1 social network, 8 posts, 4 stories, simple report.', fr: '1 reseau social, 8 posts, 4 stories, rapport simple.' },
      description: { es: 'Ideal para empezar. Incluye 1 red (IG o FB), 8 publicaciones y 4 historias al mes.', en: 'Ideal to get started. Includes 1 network (IG or FB), 8 posts and 4 stories per month.', fr: 'Ideal pour commencer. Comprend 1 reseau (IG ou FB), 8 publications et 4 stories par mois.' },
      features: [FEATURE_FLAGS.AI_MARKETING_ASSISTANT],
      agents: [{ id: 'ai_marketing_assistant', name: 'AI Marketing Assistant', enabled: true }],
      bundleId: 'bundle_social',
    },
    {
      id: 'prod_social_2',
      visible: true,
      type: 'sub',
      price: 350,
      name: { es: 'Plan Social Crecimiento', en: 'Growth Social Plan', fr: 'Plan Social Croissance' },
      badge: { es: 'Crecimiento', en: 'Growth', fr: 'Croissance' },
      note: { es: '2 redes, 12 posts, 8 historias, gestion de comentarios.', en: '2 networks, 12 posts, 8 stories, comment management.', fr: '2 reseaux, 12 posts, 8 stories, gestion des commentaires.' },
      description: { es: 'Expande tu alcance a 2 redes. Incluye 12 publicaciones, 8 historias y gestion de comentarios.', en: 'Expand your reach to 2 networks. Includes 12 posts, 8 stories and comment management.', fr: 'Etendez votre portee a 2 reseaux. Comprend 12 publications, 8 stories et gestion des commentaires.' },
      features: [FEATURE_FLAGS.AI_CONTENT_GENERATION, FEATURE_FLAGS.CRM_LIGHT],
    },
    {
      id: 'prod_social_3',
      visible: true,
      type: 'sub',
      price: 850,
      name: { es: 'Plan Social Pro', en: 'Pro Social Plan', fr: 'Plan Social Pro' },
      badge: { es: 'Pro', en: 'Pro', fr: 'Pro' },
      note: { es: '3 redes, 20 posts, reels, optimizacion IA, soporte prioritario.', en: '3 networks, 20 posts, reels, AI optimization, priority support.', fr: '3 reseaux, 20 posts, reels, optimisation IA, support prioritaire.' },
      description: { es: 'Dominio en 3 redes con 20 publicaciones, 12 historias, reels y soporte prioritario.', en: 'Dominate 3 networks with 20 posts, 12 stories, reels and priority support.', fr: 'Dominez 3 reseaux avec 20 publications, 12 stories, reels et support prioritaire.' },
      features: [FEATURE_FLAGS.AI_CONTENT_SCHEDULER, FEATURE_FLAGS.AI_CAMPAIGN_PLANNER, FEATURE_FLAGS.ANALYTICS_INTEGRATION],
    },
    {
      id: 'prod_ai_agent',
      visible: true,
      type: 'sub',
      price: 200,
      name: { es: 'Agente IA 24/7', en: 'AI Agent 24/7', fr: 'Agent IA 24/7' },
      badge: { es: 'IA', en: 'AI', fr: 'IA' },
      note: { es: 'Atencion automatizada por WhatsApp, Messenger e Instagram DMs.', en: 'Automated support via WhatsApp, Messenger and Instagram DMs.', fr: 'Support automatise via WhatsApp, Messenger et Instagram DMs.' },
      description: { es: 'Agente conversacional con IA para atender a tus clientes en todos los canales de mensajeria.', en: 'Conversational AI agent to serve your customers across all messaging channels.', fr: 'Agent conversationnel IA pour servir vos clients sur tous les canaux de messagerie.' },
      features: [FEATURE_FLAGS.AI_MARKETING_ASSISTANT],
      agents: [{ id: 'ai_marketing_assistant', name: 'AI Marketing Assistant', enabled: true }],
    },
  ],
  bundles: [
    {
      id: 'bundle_social',
      visible: true,
      name: { es: 'Bundle Social', en: 'Social Bundle', fr: 'Bundle Social' },
      description: { es: 'Todos los planes sociales con IA y analitica.', en: 'All social plans with AI and analytics.', fr: 'Tous les plans sociaux avec IA et analytique.' },
      products: ['prod_social_1', 'prod_social_2', 'prod_social_3'],
      services: ['solution-sm'],
      features: [FEATURE_FLAGS.AI_MARKETING_ASSISTANT, FEATURE_FLAGS.ANALYTICS_INTEGRATION],
      agents: [
        { id: 'ai_marketing_assistant', name: 'AI Marketing Assistant', enabled: true },
        { id: 'crm_bot', name: 'CRM Bot', enabled: false },
      ],
    },
  ],
};
